version: 1.0.{build}
image:
- Visual Studio 2017
artifacts:
- path: jupyterq_windows-$(appveyor_repo_tag_name).zip
skip_non_tags: false
platform: x64
build_script:
- cmd: >-

    build\compile.bat

    build\getkdb.bat

    set PATH=C:\Miniconda3-x64;C:\Miniconda3-x64\Scripts;%PATH%

    mkdir embedpy && cd embedpy && echo getembedpy"latest" | q ..\build\getembedpy.q -q && cd ..

    echo p)print('embedpy runs') | q -q

    pip install -r requirements.txt

    install.bat

    tests/test.bat

after_build:
- cmd: >-

    if "%APPVEYOR_REPO_TAG%"=="true" ( 7z a jupyterq_windows-%APPVEYOR_REPO_TAG_NAME%.zip jupyterq_*.q w64/jupyterq.dll install.bat kxpy kernelspec examples kdb+Notebooks.ipynb LICENSE README.md && appveyor PushArtifact jupyterq_windows-%APPVEYOR_REPO_TAG_NAME%.zip )

    if "%APPVEYOR_REPO_TAG%"=="false" ( 7z a jupyterq_windows-%APPVEYOR_REPO_BRANCH%-%APPVEYOR_BUILD_VERSION%.zip jupyterq_*.q w64/jupyterq.dll install.bat kxpy kernelspec LICENSE README.md examples kdb+Notebooks.ipynb && appveyor PushArtifact jupyterq_windows-%APPVEYOR_REPO_BRANCH%-%APPVEYOR_BUILD_VERSION%.zip )
deploy:
 release: $(appveyor_repo_tag_name)
 provider: GitHub
 auth_token: $(GITHUB_APIKEY)
 on:
  appveyor_repo_tag: true
 

